version: 2.1
commands:
  install_deps:
    steps:
      - restore_cache:
          keys:
            - postcode_checker-{{ checksum "Gemfile.lock" }}
            - postcode_checker-

      - run:
          name: bundle install
          command:
            bundle install --path vendor/bundle

      - save_cache:
          key: postcode_checker-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
  default_steps:
    steps:
      - checkout
      - install_deps

jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.3-node-browsers
        environment:
          - RAILS_ENV: test
          - DATABASE_USERNAME: root
          - DATABASE_HOST: 127.0.0.1
      - image: circleci/mysql:5.7.18
        environment:
          - MYSQL_ALLOW_EMPTY_PASSWORD: true
          - MYSQL_USER: root
    working_directory: ~/repo
    steps:
      - default_steps
      - run:
          name: wait for db
          command: dockerize -wait tcp://127.0.0.1:3306 -timeout 1m
      - run: bundle exec rake db:create
      - run: bundle exec rake db:migrate
      - run:
          name: run tests
          command: bundle exec rspec
      - store_test_results:
          path: /tmp/test-results
      - store_artifacts:
          path: coverage

  rubocop:
    docker:
      - image: circleci/ruby:2.6.3-node-browsers
        environment:
          REVIEWDOG_VERSION: 0.9.11
    working_directory: ~/repo
    steps:
      - default_steps
      - run:
          name: install reviewdog
          command:
            curl -fSL https://github.com/reviewdog/reviewdog/releases/download/$REVIEWDOG_VERSION/reviewdog_linux_amd64 -o reviewdog && chmod +x ./reviewdog
      - run: bundle exec rubocop --fail-level E | tee /dev/stderr | ./reviewdog -f=rubocop -reporter=github-pr-review

workflows:
  build_and_rubocop:
    jobs:
      - build
      - rubocop:
          filters:
            branches:
              ignore:
                - master
